### ISSUE TITLE
Highlighting fails often

### ISSUE THREAD

**Issue by ghost** [pablooliva/neveragain#2]
This extension looks really interesting.

It doesn't appear to do anything though. I've installed it on Firefox 75.0, and nothing is highlighted, even when I search for "Siemens" as shown in the screenshot on the Firefox addon page. What I tried:
- Go to https://duckduckgo.com/lite/
- Search for "siemens"
- Nothing is highlighted

**Comment by ghost** [comment]
Ok, it seems to work on https://duckduckgo.com (not the lite version) and Wikipedia but only *sometimes*. When I reload a page again and again, the highlighting works about half the time.

**Comment by pablooliva** [comment]
Thank you for the feedback. I upgraded to Firefox 75 and I can confirm the inconsistent loading of the add-on on Wikipedia but only on Linux. It seems to work fine on Windows. Can you give me more details about your environment by using this link https://supportdetails.com/?recipient=contact@never-aga.in

**Comment by ghost** [comment]
```
$ firefox --version
Mozilla Firefox 75.0
$ uname -a
Linux fedora 5.5.9-200.fc31.x86_64 #1 SMP Thu Mar 12 13:55:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pablooliva** [comment]
The extension should now load consistently on every page load with version 1.3 of the extension. Thank you for alerting me to this issue.
